# Generated by Django 4.0.3 on 2022-03-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomamenity_amenity_alter_roomamenity_room_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_rooms', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='wishlistroom',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_rooms', to='users.wishlist'),
        ),
    ]
