# Generated by Django 4.0.3 on 2022-03-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='rooms.amenity'),
        ),
        migrations.AlterField(
            model_name='roomamenity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomhouserule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_houserules', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_schedules', to='rooms.room'),
        ),
    ]
