# Generated by Django 4.0.3 on 2022-03-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomschedule'),
        ('reservations', '0003_remove_reservation_guests_reservationday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationitems', to='reservations.reservation')),
                ('room_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservationitems', to='rooms.room')),
            ],
            options={
                'db_table': 'reservation_items',
            },
        ),
        migrations.DeleteModel(
            name='ReservationDay',
        ),
    ]
