# Generated by Django 4.0.3 on 2022-03-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomamenity_amenity_alter_roomamenity_room_and_more'),
        ('reservations', '0004_reservationitem_delete_reservationday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='room_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_items', to='rooms.room'),
        ),
    ]
