# Generated by Django 4.0.3 on 2022-03-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cost_perfomance',
            new_name='cost_performance',
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='reviews.review'),
        ),
    ]
